version: '3.2'

services:
  postgres-facility:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: facility1
    volumes:
      - ./facility1.sql:/docker-entrypoint-initdb.d/facility1.sql
    ports:
      - "5433:5432"
  facility-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-facility
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-facility:5432/Facility1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      FACILITY_ID: 1